### PR TITLE
BUG/MEDIUM: configuration: Fix nil pointer dereference

### LINKED ISSUE #293: Dataplaneapi v2.7.3 throws SIGSEGV when starting
When starting the dataplaneapi v2.7.3, following SIGSEGV as below is thrown. With Version 2.7.2 everything works as expected. (Discovered by using latest haproxytech/haproxy-alpine containers)

Command used:
```
/usr/bin/dataplaneapi --host 127.0.0.1 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg --reload-cmd "kill -SIGUSR2 1" --restart-cmd "kill -SIGUSR2 1" --reload-delay 5
```

Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x10d9a9b]

goroutine 1 [running]:
github.com/haproxytech/dataplaneapi.SyncWithFileSettings(0xc000195080, 0xc000050130?)
	github.com/haproxytech/dataplaneapi/dataplaneapi_configuration.go:38 +0xfb
main.startServer(0xc000416a00)
	github.com/haproxytech/dataplaneapi/cmd/dataplaneapi/main.go:137 +0x7f2
main.main()
	github.com/haproxytech/dataplaneapi/cmd/dataplaneapi/main.go:59 +0x3d
```

### PR DESCRIPTION
**Pull request by mahnkong**
Hello,

This PR fixes #293 

Best regards

### CODE REVIEW

**Comment by mahnkong** [comment]
> Thanks for the PR, can you just please change the commit message to `BUG/MEDUIM: configuration: Fix nil pointer dereference` ?

@mjuraga done. :)

**Comment by vandrovisky** [comment]
Hello everything is fine?? Do you have any predictions for this fix to be implemented?

**Comment by mjuraga** [comment]
Hi @vandrovisky everything is great! The team is working hard on a couple of more issues, and once those are done and fixed we will issue a new release.

**Comment by quickchase** [comment]
Is this in the latest release? It's not in release notes, can't tell.

**Comment by mjuraga** [comment]
It's in the underlying library: https://github.com/haproxytech/client-native/commit/409813a5182d58e27e8b4e792fdb0d956181f4f1

**Pull request merged**
