### PR TITLE
MINOR: adds http-request return

### PR DESCRIPTION
**Pull request by schegi**
* adds http-request return support

### CODE REVIEW

**Comment by schegi** [comment]
Last PR to enable support for http-request return in dataplane APi, c.f. discussion https://github.com/haproxytech/dataplaneapi/issues/155.

**Comment by prometherion** [comment]
I'd suggest you splitting commits into three separate ones since the changes are involving the `DOCS`, `BUILD` and `FEATURE` areas.

**Comment by schegi** [comment]
Done, c.f. 
Doc fix: https://github.com/haproxytech/dataplaneapi/pull/169
Build goos: https://github.com/haproxytech/dataplaneapi/pull/168

**Comment by oktalz** [comment]
@schegi yes no need for multiple PRs just separate commits :)

Although separate commits helps if something particular needs to be changed (but both ways are fine)

this will be merged after we resolve some issues with Github CI we have due to recent commits.

you can resolve Conflicting files in the mean time, or I can do that after we resolve the issue

**Comment by oktalz** [comment]
CI errors have been resolved, i will merge this manually to avoid 
`Merge branch 'master' .... ` commit

**Comment by schegi** [comment]
Ah ok, thx. Sry was in my workmode. So i can avoid rebasing it. Thx again

**Comment by oktalz** [comment]
np. thank you again for the effort !
this has been merged to master directly to avoid conflicts and merge commits c743173

**Pull request closed without merging**
